package com.fit_with_friends.fitWithFriends.impl.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CONNECTION".
 */
public class Connection {

    private Long id;

    public Connection() {
    }

    public Connection(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

}
