package com.fit_with_friends.fitWithFriends.impl.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MOTIVATION".
 */
public class Motivation {

    private Long id;

    public Motivation() {
    }

    public Motivation(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

}
